[unstable]
codegen-backend = true
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[profile.server-dev]
codegen-backend = "cranelift"

[build]
rustflags = ["--cfg=has_std", "-Z", "threads=8"]
target = "x86_64-unknown-linux-gnu"
