[build]
release = false
dist = "dist"
public_url = "/"
filehash = true

[watch]
watch = []
ignore = []

[serve]
address = "127.0.0.1"
port = 42069
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = false

[tools]
wasm_bindgen = "0.2.92"
wasm_opt = "version_116"
tailwindcss = "3.4.3"
